### ISSUE TITLE
Implement the Receiving Mode

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#1]
- [x] The P2P  will have a user interface to activating sending or receiving mode using buttons.

![image](https://user-images.githubusercontent.com/25123762/53865727-f10f4c00-4000-11e9-9ffd-ee5a0993e53f.png)

- [x] On clicking the receive mode the device will start advertisin. 

- [x] P2P_STAR should be used as the strategy

- [x] After starting adverting then the buttons will be hidden and a progress dialog will be shown that notifies the user that the device waits for a sender.

- [x] A cancel button will be displayed below the progress  dialog above that when clicked stops the device from advertising itself.

**Comment by ekigamba** [comment]
My idea around this is that this activity will have all the views between choosing the sync mode and authorization

1.  The initial view above
2. The progress dialog when waiting for the sender
3. The views to be shown when a discoverer initiates a connection with the device
4. Views to be show for authentication
5. Views for authorization
