### ISSUE TITLE
Create Interface for receiving data

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#11]
The P2P library will define an interface that will be implemented by the host application for processing received  data .

```
int receiveJSON(DataType type, JSONArray jsonArray);

boolean receiveMultiMedia(DataType type, File file);
```

- [x] The P2PLibrary will invoke `receiveJSON`  with a JsonArray and  data type. The Host application should process the JSONArray and return the lastRecordId that was processed for that JSONArray.

- [x] The P2PLibary will invoke `receiveMultiMedia` with the multimedia File that was received. The host application should process the file and return a true if successful.

- [x] The P2PLibrary will update the lastRecordID for each data type received above in the table `p2p_received_history`

**Comment by ekigamba** [comment]
I will add

```java

    @WorkerThread
    TreeSet<DataType> getDataTypes();
```

so that in case the receiver has no record, then we get the list of data types from the sender and we can also use it for counter-checking that the data type is available from the sender
