### ISSUE TITLE
Implement Sending data

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#14]
- [x] The P2P Library will have a batchSize that will be configurable from the HostApplication.

- [x] The P2PLibrary will invoke the `getDataTypes`, the host app returns the various types of data that should be sent e.g EventClient,Tasks, Structures, ProfileImages  

- [x] The P2PLibrary will use the lastRecordID for each type from the receiver as on [https://github.com/OpenSRP/opensrp-client-p2p/issues/8](https://github.com/OpenSRP/opensrp-client-p2p/issues/8)

Below will be Order for Sending for various objects

1. Event Client JSON to be generated by the sending client and sent via Stream Payload.
2. Multimedia files to be shared via a Stream Payload.

When sending loop through the datatypes that are  applicable for sending. Consider order above
 
1. Invoke `getJSONData`  with the `lastRecordID` for 1 to 3 above  to get a batch of JSONArray .
2. Write the JSON to an input stream . 
3. Compress the  input stream and create a Stream Payload. 
4. Create a [manifest](https://github.com/OpenSRP/opensrp-client-p2p/issues/12) for the payload and send 
5. Send the payload
6. Increment the lastRecordID and Invoke 1 again. If no data is returned go the the next data type e.g Task until all datatypes have been sent.

For sending multimedia objects one multimedia file is sent at a time. The assumption is that multimedia details files are tracked on at database. The process will be

1. The P2PLibary will invoke `getMultiMediaData` to get multimedia File.
2. Create a Stream Payload for the file. 
3. Create a [manifest](https://github.com/OpenSRP/opensrp-client-p2p/issues/12) for the payload and send 
4. Send the payload
5. Increment the lastRecordID and Invoke 1 again. If no data is returned sending has completed

**Comment by ekigamba** [comment]
We should also have a way to notify the receiving device that the sending of data has completed, this will also be able to account for the state where there is not data to send

**Comment by ekigamba** [comment]
@githengi Are we supposed to rely on the library incrementing the `lastRecordId` or can we have the host application return the highestRecordId from the data set it provided us?

I am not sure I understand how this lastRecordId is specifically used and not sure how accurate it would be if the library handles the lastRecordId for every batch without consultation with the host application which is providing the records

**Comment by githengi** [comment]
The host application should return the `lastRecordId` for each batch it returns
