### ISSUE TITLE
Implement Authentication on Receiving Device

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#3]
- [x] The P2P library will use nearby API for authentication and encryption of data being exchanged

- [x] Whenever notified whenever a Discoverer wants to connect via the `onConnectionInitiated()` callback; Render the generated authentication token using QR code and also display it somewhere is the bottom as clear text.

- [x] At the bottom of the QR code implement a button  with label `Accept connection to {deviceName} with code {Authentication code}`

- [x] On clicking the button the receiving device is deemed to have the accepted receiving from the sender.

**Comment by ekigamba** [comment]
@githengi It seems we need to enable the user reject the connection.

**Comment by githengi** [comment]
Yes

**Comment by ekigamba** [comment]
There seems to be a lot of cleanup work on the UI and UX which I think should be done after the mockups are finalised. There are gaps after accepting or rejecting a connection before the other device responds. There are also gaps between any form of communication with the nearby API. At this point, the dialogs and other loading UI are already removed and the screen seems as if it is unresponsive.

@githengi Any thoughts?
