### ISSUE TITLE
Implement Authentication on Sending Device 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/android-p2p-sync#4]
- [x] After activating [discovery mode](https://github.com/OpenSRP/opensrp-client-p2p/issues/2) Whenever   notified whenever that a nearby Advertiser is found via the onEndpointFound() callback ; the camera is opened to scan QR code.

- [x] On Scanning QR code displayed by the receiving app, then the sender is deemed to have accepted sending data.

- [x] When one cancels the QR code scanning(camera),  an alert dialog is presented with title `Accept connection to {receiver device id} ` and message `Confirm the code matches on both devices: {authentication code}`

- [x] On clicking Ok, the connection is accepted otherwise connection is rejected and user is notified

**Comment by ekigamba** [comment]
So we automatically try to connect to whichever device we find that is advertising, at which point the library tries to initiate and connection and shows the camera to check the code send?

@githengi

**Comment by githengi** [comment]
Yes try to connect to whatever device is advertising. If a device is found open camera to try scan the QR code against the generated authentication token.

**Comment by ekigamba** [comment]
There seems to be a lot of cleanup work on the UI and UX which I think should be done after the mockups are finalised. There are gaps after accepting or rejecting a connection before the other device responds. There are also gaps between any form of communication with the nearby API. At this point, the dialogs and other loading UI are already removed and the screen seems as if it is unresponsive.

@githengi Any thoughts?
