### ISSUE TITLE
Update UI design as per mockups

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/android-p2p-sync#42]
<img width="1131" alt="Screen Shot 2019-03-25 at 3 18 52 PM" src="https://user-images.githubusercontent.com/31766075/57125454-2e3e5300-6d92-11e9-9130-67e3ec4b9217.png">

**Comment by rowo** [comment]
@ekigamba some more detail on above flow with the caveat I haven't looked at where this is technically recently, so if anything works differently let me know:

<img width="1132" alt="Screen Shot 2019-05-10 at 9 27 32 PM" src="https://user-images.githubusercontent.com/1584163/57563312-7220f180-736a-11e9-9cbe-39676c2cabd7.png">

Initiate screening step is the same for both the sending (Roger) and receiving (Sam) devices.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563646-312adc00-736e-11e9-88df-afc295fed0f0.png">


For the sending device, once they tap "Send data", a dialog appears to say it's looking for a device to send to.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563299-5289c900-736a-11e9-96ed-2ce5df6ed9a2.png">

For the receiving data, a dialog appears to say it's looking for a device to receive from.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563322-8bc23900-736a-11e9-8578-36d8ec9c5861.png">

Once the devices find other devices looking to send or receive, they switch to new states. The sending device's camera is enabled and the name of the device detected that wants to receive is shown.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563523-e5c3fe00-736c-11e9-9a96-abc08d31b579.png">

The receiving device's screen shows a QR code and the sending device's name is shown.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563541-04c29000-736d-11e9-87ca-3b67ea271169.png">

The next step is showing a dialog when the partnered device choose to skip. This is only optional if the sending device is the one that wants to skip, but seems to me required if the QR (receiving) device chooses to skip.

If the receiving device chooses to skip, the sending device sees this dialog:
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563599-bfeb2900-736d-11e9-8ff6-de5e2c06f5db.png">

If the sending device chooses to skip, the receiving device sees this dialog:
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563610-d1343580-736d-11e9-8805-0a53d5724dce.png">

Once both devices agree, they see progress. I'm not sure what information is possible here, but a percent or client number of records count could make sense:
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563624-f9bc2f80-736d-11e9-8427-d3cf36c9ee0f.png">
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563626-fd4fb680-736d-11e9-82fd-a4c7779c2373.png">

At the end, you get a success screen. Information that could show here are number of records updated perhaps or maybe just the official time of end sync.
<img width="400" src="https://user-images.githubusercontent.com/1584163/57563628-0476c480-736e-11e9-966e-bd69271eaec0.png">

**Comment by ekigamba** [comment]
@rowo 

I also need a :
- Transfer fail screen because we expect the transfer to fail sometimes. It will be the same as the success screen since there might be some records that were transferred before the failure.
- Authentication failed UI in case the other device rejects the connection
- Authorization failed UI - Authorization can fail if the two devices are not on the same team


**COMMENTS ON DESIGN ABOVE**

1. I currently do not have a find-fail step in the app right now
2. Step 4 currently does not work as detailed in the design. Confirmation of the connection has to happen on both devices since it is a security risk to both. I think this needs discussion. However, I like the way you've described it, seems easier. What do you think?
3. Designs are good, I can change the remaining screens on the app to look as in the design once they are final

> Once both devices agree, they see progress. I'm not sure what information is possible here, but a percent or client number of records count could make sense:

At this point, showing the details progress such as percentage might not be technically possible. I will have to look at it a bit more

I have provided the Wcaro apk so that you can have a bit more context on what will be sent and the information available during the syncing and after.

**Comment by rowo** [comment]
@ekigamba 

1. We should discuss the security risk for the connection confirmation. Not sure who the pm is on this. 
2. I don't think progress detail is completely necessary right now — a spinner is okay in that case. If that is the case, it would be nice to give a rough sense of how long this process would take in a time range format i.e. "This usually takes between 1 and 3 minutes. Please keep the phones together during the data transfer process."

I'll put up screens/assets for the fail screens. I think they'll use the below icon with different labels.

![error-notice](https://user-images.githubusercontent.com/1584163/57699759-7416d900-7626-11e9-9ac3-491f04bbeb0a.png)

**Comment by ekigamba** [comment]
@rowo

Carolyn is the PM but Matt's taken over while she's away.

For progress details, I do not have a good idea of how long the process would take. It depends on several factors, the most important of which I do not have information about to calculate the time. 

Can you provide the options for progress details and then we can see which one is technically feasible, has the least LOE & most appropriate for the user experience & final product?  

**Brief explanation on the above**

Calculating time requires knowing the amount of data that is being transmitted by the receiver and being received on the sender. Data being received on the receiver is what we do not have as of now, I'll look at it to figure out what is possible & accurate since.

**Comment by ekigamba** [comment]
@rowo, 

I just looked at the progress details and it is possible to show the percentage progress of the current batch. 

The transfer works in batches eg. 250 records are sent for each batch until we have no more untransferred records. In this case, we can tell the progress of a single batch easily without much effort

**Comment by rowo** [comment]
Notes from our brief call:
- Include a "start transfer" step in the mockups after the QR scan so each user has to confirm to start the transfer and it doesn't go straight there after QR scan.
- If both sender and receiver decide to skip the QR scan, it can go straight to the above start transfer step without entering a code — as long as the OpenSRP username is displayed in that start transfer step.

I will update the above workflow to match. Edit: slacked @ekigamba some error messages for feedback. Edit 2: Below is a new flow with the above changes. I added step 5 and changed labels in step 3 and 4.

<img width="1320" alt="Screen Shot 2019-05-15 at 1 31 01 PM" src="https://user-images.githubusercontent.com/1584163/57796217-d26eb500-7715-11e9-9582-acea8f6c89a1.png">

![03a - Take picture of receipient QR](https://user-images.githubusercontent.com/1584163/57796279-0053f980-7716-11e9-9c57-633cde06eff2.png)

![03b - QR code for sender picture](https://user-images.githubusercontent.com/1584163/57796287-0518ad80-7716-11e9-91cc-a152861d5ce4.png)

![04a - notice of skip](https://user-images.githubusercontent.com/1584163/57796296-08139e00-7716-11e9-8de7-42801b9be05f.png)

![04b - notice of skip](https://user-images.githubusercontent.com/1584163/57796305-0a75f800-7716-11e9-9e38-c6c6d9786867.png)

![05 - start transfer](https://user-images.githubusercontent.com/1584163/57796310-0d70e880-7716-11e9-897d-79469c3eb18e.png)

**Comment by ekigamba** [comment]
Screens showing the following pages:

- Failed transfer
- Sending progress
- Receiving progress
- Successful transfer on the sender device
- Successful transfer on the receiver device

![Fail-los-during-transfer](https://user-images.githubusercontent.com/31766075/58798721-08fc6900-860c-11e9-80ad-28f867ffc754.png)
![06a - progress sending](https://user-images.githubusercontent.com/31766075/58798720-0863d280-860c-11e9-81aa-71698657f686.png)
![06b - progress receiving](https://user-images.githubusercontent.com/31766075/58798719-0863d280-860c-11e9-90ba-59c5c6003d72.png)
![07 - Send - success](https://user-images.githubusercontent.com/31766075/58798718-0863d280-860c-11e9-9356-a3bc23409fc2.png)
![07 - Receive - success](https://user-images.githubusercontent.com/31766075/58798717-07cb3c00-860c-11e9-975d-c9e05bbf4cc4.png)

Provided by @rowo

**Comment by hngondoki** [comment]
The QA for this has passed.
![IMG_2145](https://user-images.githubusercontent.com/18394882/59493458-82f5e300-8e93-11e9-8ded-541b29eb18ea.JPG)
![IMG_2160](https://user-images.githubusercontent.com/18394882/59493507-a7ea5600-8e93-11e9-948a-36d3ab228ed7.JPG)
![IMG_2157](https://user-images.githubusercontent.com/18394882/59493466-89845a80-8e93-11e9-85fc-1ec3804e049e.JPG)
![IMG_2166](https://user-images.githubusercontent.com/18394882/59495529-20531600-8e98-11e9-9493-06a4e1502b30.JPG)
![IMG_2161](https://user-images.githubusercontent.com/18394882/59494426-c5b8ba80-8e95-11e9-9b23-6c94309d0a19.JPG)
![IMG_2168](https://user-images.githubusercontent.com/18394882/59496087-5f359b80-8e99-11e9-8782-6d61dee941cd.JPG)

**Comment by hngondoki** [comment]
@ekigamba issue raised on alignment of screen elements https://github.com/OpenSRP/android-p2p-sync/issues/61
