### ISSUE TITLE
After adding 1 profile picture, sync shows 2 profile-pic count

### ISSUE THREAD

**Issue by hngondoki** [OpenSRP/android-p2p-sync#59]
After adding 1 profile picture for Kofi Sofi under Wofi Familt, sync shows 2 profile-pic count. Consider making the page scrollable.No of  Client records was not viewable in one device.
![IMG_2135](https://user-images.githubusercontent.com/18394882/59207322-85182300-8baf-11e9-9d89-53eb79ac62f6.JPG)

**Comment by ekigamba** [comment]
@hmakandi I have confirmed this behaviour. Updating a child registration by adding a profile picture creates two profile pictures. This issue should be filed under the client application and is not necessarily a peer-to-peer issue

Thanks for noticing that, I expected only one profile picture to be created
