### ISSUE TITLE
Synced data does not process as expected

### ISSUE THREAD

**Issue by hngondoki** [OpenSRP/android-p2p-sync#62]
After updating the immunization records of baby Victor Beyan. The original device shows that Vitamin A is overdue and the master device shows BCG is overdue.

To replicate,fill in immunization details of child, and then sync the data.

- [ ] Fixing misalignment and processing of synced data 
![IMG_2186](https://user-images.githubusercontent.com/18394882/59497545-58f4ee80-8e9c-11e9-85cb-c909a531ff64.JPG)

**Comment by cafootitt** [comment]
@hmakandi Can you post the screenshots of the two upcoming services pages as well? If the information displayed is the same for both, then this becomes a lower priority issue.

**Comment by ekigamba** [comment]
This has been reported to the CHW team which is investigating and working on this
Cc @rkodev

**Comment by ekigamba** [comment]
This has been reported to the CHW team since it is not a peer-to-peer issue. 
Cc @rkodev

**Comment by ekigamba** [comment]
@cafootitt the upcoming services pages do not show the same information
This issue has been moved to https://github.com/OpenSRP/opensrp-client-chw/issues/438
